// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, passwd)
VALUES (?, ?)
RETURNING id, username, passwd
`

type CreateUserParams struct {
	Username string
	Passwd   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Passwd)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Passwd)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, passwd FROM users
WHERE users.username = ?1 AND users.passwd = ?2 
LIMIT 1
`

type GetUserParams struct {
	Username string
	Passwd   string
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, arg.Username, arg.Passwd)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Passwd)
	return i, err
}
